### ISSUE TITLE
横屏显示有问题

### ISSUE THREAD

**Issue by subite0** [alibaba/youku-sdk-tool-woodpecker#1]
ipad横屏显示有问题

**Comment by ZimWoodpecker** [comment]
可以截图具体说明一下吗

**Comment by subite0** [comment]
使用ipad新建个项目，设备方向只支持横屏，pod引入后直接调用show方法就出现。

![IMG_0062](https://user-images.githubusercontent.com/34902829/72677081-6b3ea700-3ad3-11ea-9f64-0b5205ff0db9.PNG)

**Comment by ZimWoodpecker** [comment]
可以用最新1.1.3版本试一下，做了一些适配。

**Comment by subite0** [comment]
en, 非常感谢你及时的更新，整体的方向已经改过来了，但是又发现了另一个小问题，在显示cpu,内存，FPS和网络流量view的时候，方向还有有小问题的，会竖方向显示，看多了可以锻炼颈椎😆

![IMG_0080](https://user-images.githubusercontent.com/34902829/72704954-15323800-3b95-11ea-826f-4bba2580b6e1.PNG)

**Comment by ZimWoodpecker** [comment]
1.2.0 版修复了转屏、启动等问题，更新一下试试
