### ISSUE TITLE
Got any plan for New Build System?

### ISSUE THREAD

**Issue by chimingzi** [alibaba/youku-sdk-tool-woodpecker#12]
I'm working on the iOS-->Catalyst adaption, the catalyst project only supports New Build System.
Got any plan for New Build System?

**Comment by ZimWoodpecker** [comment]
Currently the project is running on the New Build System, is there any problem when running woodpecker in your project?

**Comment by chimingzi** [comment]
> Currently the project is running on the New Build System, is there any problem when running woodpecker in your project?

Thanks for reply,it's my mistake.
After remove duplicate  Assets in [Copy Bundle Resources], the New Building System works!
