### ISSUE TITLE
xcassets和New build system的问题

### ISSUE THREAD

**Issue by AiweiChujian** [alibaba/youku-sdk-tool-woodpecker#13]
首先，非常感谢你们开源的这款工具，它简洁明了的特性让人非常的喜欢，然后就是在使用过程中遇见个小问题，希望在后续更新的版本中能优化一下：podspec中使用resource来引用了xcassets，导致通过cocopods以静态库的方式引入此工具的时候，New build system下会编译失败，而我又不想放弃使用New build system，希望后续版本能通过resource_bundle来引用xcassets，或通过其他方式管理图片。

**Comment by ZimWoodpecker** [comment]
我修改了一下图片引用方式，不使用xcassets了，1.2.9版本你试一下吧

**Comment by AiweiChujian** [comment]
谢谢🤝
