### ISSUE TITLE
启动崩溃

### ISSUE THREAD

**Issue by Ccct** [alibaba/youku-sdk-tool-woodpecker#3]
走到这句代码的时候
[[UIApplication sharedApplication].windows.firstObject makeKeyAndVisible];

奔溃：
Thread 1: Exception: "[<UIViewController 0x107a16340> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key scrollView."

**Comment by ZimWoodpecker** [comment]
我这里没有复现，可以提供下Xcode和测试机版本号吗
