### ISSUE TITLE
Multiple commands produce

### ISSUE THREAD

**Issue by Hank-Zhong** [alibaba/youku-sdk-tool-woodpecker#4]
在Xcode Version 11.4 (11E146)环境下会报：
Multiple commands produce '/Users/xxx/Library/Developer/Xcode/DerivedData/xxx-bagyiuswypqmbecbiulvoyoopfwt/Build/Products/Debug-iphoneos/xxxx.app/Assets.car':
1) Target 'xxx' (project 'xxx') has compile command with input '/Users/xxx/Desktop/"xxx"/"xxx"/Main/Assets.xcassets'
2) That command depends on command in Target 'xxx' (project 'xxx'): script phase “[CP] Copy Pods Resources”

错误！
目前是参考此[方法](https://stackoverflow.com/a/60107620)解决的

**Comment by ZimWoodpecker** [comment]
已按照你提供的方法修复此问题，谢谢~
