### ISSUE TITLE
无法弹出UIMenuController问题及解决办法

### ISSUE THREAD

**Issue by Hank-Zhong** [alibaba/youku-sdk-tool-woodpecker#5]
执行`[[YKWoodpeckerManager sharedInstance] show];`是在`self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];`之后，会出现无法弹出UIMenuController问题。
在`self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];`之前show即可解决

**Comment by ZimWoodpecker** [comment]
👍

**Comment by Hank-Zhong** [comment]
> 👍

但是如果需要动态隐藏和显示，调用`hide`之后在其它地方再次调用`show`还是会导致无法弹出UIMenuController问题。

**Comment by ZimWoodpecker** [comment]
啄幕鸟显示为keywindow导致的，最新1.2.3版已修复UIMenuController问题。

**Comment by madonya** [comment]
> 啄幕鸟显示为keywindow导致的，最新1.2.3版已修复UIMenuController问题。

使用1.2.3版本依然无法弹出

**Comment by ZimWoodpecker** [comment]
我这边demo工程可以弹出，你的测试机是什么版本的

**Comment by madonya** [comment]
13.3.1
