### ISSUE TITLE
YKWObjcMethodHookDelegate中

### ISSUE THREAD

**Issue by sp55** [alibaba/youku-sdk-tool-woodpecker#6]
http://q9htijk01.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202020-04-28%2016.21.39.png

这里加个判空吧，不知道是不是我这边接口太多了，崩在这里了

**Comment by ZimWoodpecker** [comment]
1.2.4 已添加
