### ISSUE TITLE
UIImage Gategory问题

### ISSUE THREAD

**Issue by MNZhu** [alibaba/youku-sdk-tool-woodpecker#7]
1.UIImage分类，颜色转图片，转出来的效果是错误的,且覆盖了项目中同样名称的分类方法。
2.如果分类不是和框架功能同样开放使用的，建议自定义个命名空间。
3.YYKit也是出自优酷吧，建议参考YYKit中UIImage分类的实现方式，很严谨。
4.建议加上release版本的排除方法，如FLEX的方式。

**Comment by ZimWoodpecker** [comment]
Category同名问题已解决，Release排除可以用DEBUG宏解决，啄幕鸟代码都是安全的，Release版本也可以打进去，这块没有限制

**Comment by MNZhu** [comment]
作者手速很快啊
