### ISSUE TITLE
demo无法运行，提示pod库丢失

### ISSUE THREAD

**Issue by wanduwt** [alibaba/youku-sdk-tool-woodpecker#9]
demo无法运行，拉取到本地pod库的颜色是淡蓝色的，提示报错。

**Comment by ZimWoodpecker** [comment]
执行pod update之后无法运行吗

**Comment by wanduwt** [comment]
pod update可以运行了，希望能直接在线上解决

**Comment by ZimWoodpecker** [comment]
把其他库也包含的话git库会变得比较大，第三方库一般gitignore，我在readme里说明一下如何运行demo吧。
